#!/bin/bash
# =============================================================================
# MuduoChatServer 集群管理脚本
#
# 用法:
#   ./cluster.sh start 3          # 启动 3 节点集群 + 更新 Nginx
#   ./cluster.sh start 5 6000     # 启动 5 节点，从 6000 端口开始
#   ./cluster.sh stop             # 停止全部
#   ./cluster.sh status           # 查看集群状态
#   ./cluster.sh add 6003         # 热添加一个节点（自动更新 Nginx）
#   ./cluster.sh del 6002         # 热移除一个节点（自动更新 Nginx）
# =============================================================================

set -e

BIN="$(cd "$(dirname "$0")" && pwd)/bin"
NGINX_CONF="$(cd "$(dirname "$0")" && pwd)/nginx.conf"
NGINX_UPSTREAM="/tmp/nginx_chatserver_upstream.conf"
PID_DIR="/tmp/muduo_chat"
mkdir -p "$PID_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ========== 生成 Nginx upstream 配置 ==========
generate_nginx_upstream() {
    local ports=("$@")
    if [ ${#ports[@]} -eq 0 ]; then
        echo "Error: no backend servers" >&2
        return 1
    fi

    cat > "$NGINX_UPSTREAM" << 'STREAM_HEADER'
# Auto-generated by cluster.sh — DO NOT EDIT MANUALLY

stream {
    log_format tcp '$remote_addr [$time_local] '
                   '$protocol $status $bytes_sent $bytes_received '
                   '$session_time "$upstream_addr"';
    access_log /var/log/nginx/stream_access.log tcp buffer=32k;

    upstream chatserver_backend {
        least_conn;
STREAM_HEADER

    for port in "${ports[@]}"; do
        echo "        server 127.0.0.1:$port max_fails=3 fail_timeout=30s;" >> "$NGINX_UPSTREAM"
    done

    cat >> "$NGINX_UPSTREAM" << 'STREAM_FOOTER'
    }

    server {
        listen 8000;
        proxy_pass chatserver_backend;
        proxy_connect_timeout 5s;
        proxy_timeout 600s;
        proxy_buffer_size 16k;
    }
}
STREAM_FOOTER

    echo "  [nginx] upstream config generated: ${ports[*]}"
}

# ========== 重载 Nginx ==========
reload_nginx() {
    if command -v nginx &>/dev/null && nginx -t -c "$NGINX_UPSTREAM" 2>/dev/null; then
        # Nginx 已运行 → 热重载
        if nginx -s reload 2>/dev/null; then
            echo "  [nginx] hot reloaded with new upstream"
        else
            # 未运行 → 启动
            nginx -c "$NGINX_UPSTREAM" 2>/dev/null && echo "  [nginx] started" || true
        fi
    else
        echo -e "  ${YELLOW}[nginx] not available — skip (clients connect directly to server ports)${NC}"
    fi
}

# ========== 启动集群 ==========
cmd_start() {
    local count=${1:-3}
    local base_port=${2:-6000}

    echo -e "${GREEN}=== Starting $count-node cluster (ports $base_port-$((base_port + count - 1))) ===${NC}"

    # 1. 确保 MySQL + Redis 在线状态正确
    mysql -u root -p123456 chat -e "UPDATE user SET state=0 WHERE state=1;" 2>/dev/null && \
        echo "  [db] user states reset" || echo -e "  ${YELLOW}[db] MySQL not available — skip${NC}"

    # 2. 收集端口列表
    local ports=()
    for ((i = 0; i < count; i++)); do
        local port=$((base_port + i))
        ports+=($port)

        # 杀掉该端口旧进程
        fuser -k ${port}/tcp 2>/dev/null && sleep 0.5 || true

        # 启动 ChatServer
        $BIN/ChatServer 0.0.0.0 $port > /tmp/chat_server_${port}.log 2>&1 &
        echo $! > "$PID_DIR/server_${port}.pid"
        echo "  [$i] ChatServer :$port started (PID $(cat $PID_DIR/server_${port}.pid))"
    done

    sleep 1

    # 3. 生成 Nginx upstream + 重载
    generate_nginx_upstream "${ports[@]}"
    reload_nginx

    echo ""
    echo -e "${GREEN}=== Cluster ready: $count nodes ===${NC}"
    echo "  Client connect: ./bin/ChatClient <nginx_ip> 8000"
    echo "  Or direct:       ./bin/ChatClient 127.0.0.1 $base_port"
}

# ========== 停止集群 ==========
cmd_stop() {
    echo -e "${RED}=== Stopping cluster ===${NC}"

    for pid_file in "$PID_DIR"/server_*.pid; do
        [ -f "$pid_file" ] || continue
        local pid=$(cat "$pid_file")
        local port=$(basename "$pid_file" .pid | sed 's/server_//')
        if kill "$pid" 2>/dev/null; then
            echo "  [$port] stopped (PID $pid)"
        fi
        rm -f "$pid_file"
    done

    # 清理残留
    for port in $(seq 6000 6010); do
        fuser -k ${port}/tcp 2>/dev/null || true
    done

    rm -f "$NGINX_UPSTREAM"
    echo "  All nodes stopped."
}

# ========== 查看状态 ==========
cmd_status() {
    echo -e "${YELLOW}=== Cluster Status ===${NC}"
    local running=0

    for pid_file in "$PID_DIR"/server_*.pid; do
        [ -f "$pid_file" ] || continue
        local pid=$(cat "$pid_file")
        local port=$(basename "$pid_file" .pid | sed 's/server_//')

        if kill -0 "$pid" 2>/dev/null; then
            local rss=$(awk '/VmRSS/{printf "%.0f MB", $2/1024}' /proc/$pid/status 2>/dev/null || echo "?")
            local fd=$(ls /proc/$pid/fd 2>/dev/null | wc -l)
            echo -e "  ${GREEN}[ON]${NC}  :$port  PID=$pid  RSS=$rss  FDs=$fd"
            ((running++))
        else
            echo -e "  ${RED}[OFF]${NC} :$port (stale pid file)"
            rm -f "$pid_file"
        fi
    done

    if [ $running -eq 0 ]; then
        echo "  (no nodes running)"
    else
        echo "  Total: $running node(s)"
        echo ""
        echo "  Client entry: $(hostname -I 2>/dev/null | awk '{print $1}' || echo 'localhost'):8000"
    fi
}

# ========== 热添加节点 ==========
cmd_add() {
    local port=$1
    if [ -z "$port" ]; then
        echo "Usage: $0 add <port>" >&2
        exit 1
    fi

    echo -e "${GREEN}=== Hot-adding node :$port ===${NC}"

    $BIN/ChatServer 0.0.0.0 $port > /tmp/chat_server_${port}.log 2>&1 &
    echo $! > "$PID_DIR/server_${port}.pid"
    echo "  ChatServer :$port started (PID $(cat $PID_DIR/server_${port}.pid))"

    # 重建 upstream（包含新节点）
    local ports=()
    for pid_file in "$PID_DIR"/server_*.pid; do
        [ -f "$pid_file" ] || continue
        local p=$(basename "$pid_file" .pid | sed 's/server_//')
        ports+=($p)
    done
    # 排序
    IFS=$'\n' ports=($(sort -n <<<"${ports[*]}")); unset IFS

    generate_nginx_upstream "${ports[@]}"
    reload_nginx

    echo "  Done. New upstream: ${ports[*]}"
}

# ========== 热移除节点 ==========
cmd_del() {
    local port=$1
    if [ -z "$port" ]; then
        echo "Usage: $0 del <port>" >&2
        exit 1
    fi

    echo -e "${RED}=== Hot-removing node :$port ===${NC}"

    local pid_file="$PID_DIR/server_${port}.pid"
    if [ -f "$pid_file" ]; then
        local pid=$(cat "$pid_file")
        kill "$pid" 2>/dev/null && echo "  [$port] stopped (PID $pid)" || echo "  [$port] already dead"
        rm -f "$pid_file"
    else
        fuser -k ${port}/tcp 2>/dev/null && echo "  [$port] killed by port" || echo "  [$port] not running"
    fi

    # 重建 upstream（移除该节点）
    local ports=()
    for pf in "$PID_DIR"/server_*.pid; do
        [ -f "$pf" ] || continue
        local p=$(basename "$pf" .pid | sed 's/server_//')
        ports+=($p)
    done
    IFS=$'\n' ports=($(sort -n <<<"${ports[*]}")); unset IFS

    if [ ${#ports[@]} -gt 0 ]; then
        generate_nginx_upstream "${ports[@]}"
        reload_nginx
        echo "  New upstream: ${ports[*]}"
    else
        rm -f "$NGINX_UPSTREAM"
        echo "  No nodes left. Nginx upstream removed."
    fi
}

# ========== 入口 ==========
case "${1:-}" in
    start)  cmd_start "${2:-3}" "${3:-6000}" ;;
    stop)   cmd_stop ;;
    status) cmd_status ;;
    add)    cmd_add "$2" ;;
    del)    cmd_del "$2" ;;
    *)
        echo "Usage: $0 {start|stop|status|add|del} [args...]"
        echo ""
        echo "  start [count] [base_port]  启动集群（默认3节点，从6000开始）"
        echo "  stop                       停止所有节点"
        echo "  status                     查看集群状态"
        echo "  add <port>                 热添加节点（自动更新 Nginx）"
        echo "  del <port>                 热移除节点（自动更新 Nginx）"
        echo ""
        echo "Examples:"
        echo "  $0 start                    # 3节点: 6000, 6001, 6002"
        echo "  $0 start 5                  # 5节点: 6000~6004"
        echo "  $0 start 3 7000             # 3节点: 7000, 7001, 7002"
        echo "  $0 add 6005                 # 扩容"
        echo "  $0 del 6001                 # 缩容"
        exit 1
        ;;
esac
